### ISSUE TITLE
Trying to run chessgraph script on windows x86 (6.1.7601) 64-bit platform got error message.

### ISSUE THREAD

**Issue by LazyFrankB** [vondele/chessgraph#5]
C:\...\chessgraph>python chessgraph.py --alpha -135 --beta -110 --depth 9 --boardstyle none --san "1. g4 d5 2. e3"
Traceback (most recent call last):
  File "chessgraph.py", line 14, in <module>
    import cairosvg
  File "C:\Users\Raivis\AppData\Local\Programs\Python\Python38-32\lib\site-packa
ges\cairosvg__init.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Raivis\AppData\Local\Programs\Python\Python38-32\lib\site-packa
ges\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Raivis\AppData\Local\Programs\Python\Python38-32\lib\site-packa
ges\cairocffi__init.py", line 47, in <module>
    cairo = dlopen(
  File "C:\Users\Raivis\AppData\Local\Programs\Python\Python38-32\lib\site-packa
ges\cairocffi__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "libcairo-2" was found
cannot load library 'C:\Program Files\Graphviz\bin\cairo.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by vondele** [comment]
this is an error due to missing (or incorrectly installed) dependencies:
did you install the https://github.com/vondele/chessgraph/blob/main/requirements.txt ?
(something like `pip install -r requirements.txt` should work)

**Comment by LazyFrankB** [comment]
Yes, all requirements satisfied.

C:\Users\Raivis\Documents\GitHub\chessgraph>pip install -r requirements.txt
Requirement already satisfied: graphviz in c:\users\raivis\appdata\local\program
s\python\python38-32\lib\site-packages (from -r requirements.txt (line 1)) (0.20
.1)
Requirement already satisfied: cairosvg in c:\users\raivis\appdata\local\program
s\python\python38-32\lib\site-packages (from -r requirements.txt (line 2)) (2.7.
0)
Requirement already satisfied: requests in c:\users\raivis\appdata\local\program
s\python\python38-32\lib\site-packages (from -r requirements.txt (line 3)) (2.28
.2)
Requirement already satisfied: chess in c:\users\raivis\appdata\local\programs\p
ython\python38-32\lib\site-packages (from -r requirements.txt (line 4)) (1.9.4)
Requirement already satisfied: cairocffi in c:\users\raivis\appdata\local\progra
ms\python\python38-32\lib\site-packages (from cairosvg->-r requirements.txt (lin
e 2)) (1.5.1)
Requirement already satisfied: cssselect2 in c:\users\raivis\appdata\local\progr
ams\python\python38-32\lib\site-packages (from cairosvg->-r requirements.txt (li
ne 2)) (0.7.0)
Requirement already satisfied: defusedxml in c:\users\raivis\appdata\local\progr
ams\python\python38-32\lib\site-packages (from cairosvg->-r requirements.txt (li
ne 2)) (0.7.1)
Requirement already satisfied: pillow in c:\users\raivis\appdata\local\programs\
python\python38-32\lib\site-packages (from cairosvg->-r requirements.txt (line 2
)) (9.5.0)
Requirement already satisfied: tinycss2 in c:\users\raivis\appdata\local\program
s\python\python38-32\lib\site-packages (from cairosvg->-r requirements.txt (line
 2)) (1.2.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\raivis\appda
ta\local\programs\python\python38-32\lib\site-packages (from requests->-r requir
ements.txt (line 3)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raivis\appdata\local\pro
grams\python\python38-32\lib\site-packages (from requests->-r requirements.txt (
line 3)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\raivis\appdata\
local\programs\python\python38-32\lib\site-packages (from requests->-r requireme
nts.txt (line 3)) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raivis\appdata\loc
al\programs\python\python38-32\lib\site-packages (from requests->-r requirements
.txt (line 3)) (2022.12.7)
Requirement already satisfied: cffi>=1.1.0 in c:\users\raivis\appdata\local\prog
rams\python\python38-32\lib\site-packages (from cairocffi->cairosvg->-r requirem
ents.txt (line 2)) (1.15.1)
Requirement already satisfied: webencodings in c:\users\raivis\appdata\local\pro
grams\python\python38-32\lib\site-packages (from cssselect2->cairosvg->-r requir
ements.txt (line 2)) (0.5.1)
Requirement already satisfied: pycparser in c:\users\raivis\appdata\local\progra
ms\python\python38-32\lib\site-packages (from cffi>=1.1.0->cairocffi->cairosvg->
-r requirements.txt (line 2)) (2.21)

**Comment by vondele** [comment]
Since I don't have windows, I can't test, but https://cairosvg.org/documentation/ suggests that:
```
CairoSVG and its dependencies may require additional tools during the installation: a compiler, Python headers, Cairo, and FFI headers. These tools have different names depending on the OS you are using, but:

    on Windows, you’ll have to install Visual C++ compiler for Python and Cairo;
    on macOS, you’ll have to install cairo and libffi (with [Homebrew](https://brew.sh/) for example);
    on Linux, you’ll have to install the cairo, python3-dev and libffi-dev packages (names may vary for your distribution).

If you don’t know how to install these tools, you can follow the simple steps of [WeasyPrint’s installation guide](http://weasyprint.readthedocs.io/en/latest/install.html): installing WeasyPrint will also install CairoSVG.
```
Maybe somebody with a windows environment can provide a hint?

**Comment by robertnurnberg** [comment]
Maybe @LazyFrankB can first try to follow the steps [here](http://weasyprint.readthedocs.io/en/latest/install.html) to install WeasyPrint? Let us know...

**Comment by LazyFrankB** [comment]
Did following:

(venv) C:\Users\Raivis>python -m pip install weasyprint
Requirement already satisfied: weasyprint in c:\users\raivis\venv\lib\site-packa
ges (59.0)
Requirement already satisfied: cssselect2>=0.1 in c:\users\raivis\venv\lib\site-
packages (from weasyprint) (0.7.0)
Requirement already satisfied: Pyphen>=0.9.1 in c:\users\raivis\venv\lib\site-pa
ckages (from weasyprint) (0.14.0)
Requirement already satisfied: fonttools[woff]>=4.0.0 in c:\users\raivis\venv\li
b\site-packages (from weasyprint) (4.39.4)
Requirement already satisfied: html5lib>=1.1 in c:\users\raivis\venv\lib\site-pa
ckages (from weasyprint) (1.1)
Requirement already satisfied: pydyf>=0.6.0 in c:\users\raivis\venv\lib\site-pac
kages (from weasyprint) (0.6.0)
Requirement already satisfied: tinycss2>=1.0.0 in c:\users\raivis\venv\lib\site-
packages (from weasyprint) (1.2.1)
Requirement already satisfied: Pillow>=9.1.0 in c:\users\raivis\venv\lib\site-pa
ckages (from weasyprint) (9.5.0)
Requirement already satisfied: cffi>=0.6 in c:\users\raivis\venv\lib\site-packag
es (from weasyprint) (1.15.1)
Requirement already satisfied: webencodings in c:\users\raivis\venv\lib\site-pac
kages (from cssselect2>=0.1->weasyprint) (0.5.1)
Requirement already satisfied: brotli>=1.0.1; platform_python_implementation ==
"CPython" and extra == "woff" in c:\users\raivis\venv\lib\site-packages (from fo
nttools[woff]>=4.0.0->weasyprint) (1.0.9)
Requirement already satisfied: zopfli>=0.1.4; extra == "woff" in c:\users\raivis
\venv\lib\site-packages (from fonttools[woff]>=4.0.0->weasyprint) (0.2.2)
Requirement already satisfied: six>=1.9 in c:\users\raivis\venv\lib\site-package
s (from html5lib>=1.1->weasyprint) (1.16.0)
Requirement already satisfied: pycparser in c:\users\raivis\venv\lib\site-packag
es (from cffi>=0.6->weasyprint) (2.21)

(venv) C:\Users\Raivis>python -m weasyprint --info

-----

WeasyPrint could not import some external libraries. Please carefully follow the
 installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting


-----

Traceback (most recent call last):
  File "C:\Users\Raivis\AppData\Local\Programs\Python\Python38-32\lib\runpy.py",
 line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Raivis\AppData\Local\Programs\Python\Python38-32\lib\runpy.py",
 line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Raivis\AppData\Local\Programs\Python\Python38-32\lib\runpy.py",
 line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Raivis\venv\lib\site-packages\weasyprint\__init__.py", line 387
, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\Raivis\venv\lib\site-packages\weasyprint\css\__init__.py", line
 25, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\Raivis\venv\lib\site-packages\weasyprint\css\computed_values.py
", line 11, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\Users\Raivis\venv\lib\site-packages\weasyprint\text\ffi.py", line 428
, in <module>
    gobject = _dlopen(
  File "C:\Users\Raivis\venv\lib\site-packages\weasyprint\text\ffi.py", line 417
, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\Users\Raivis\venv\lib\site-packages\cffi\api.py", line 150, in dlopen

    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\Raivis\venv\lib\site-packages\cffi\api.py", line 832, in _make_
ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\Raivis\venv\lib\site-packages\cffi\api.py", line 827, in _load_
backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.
util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by robertnurnberg** [comment]
Just by chance, does chessgraph work now?

**Comment by LazyFrankB** [comment]
Nope, the same error message, but indeed seems problem is on CairoSVG and/or WeasyPrint side.

**Comment by robertnurnberg** [comment]
Maybe this helps: [stackoverflow](https://stackoverflow.com/questions/69067530/how-to-solve-weasyprint-error-message-gobject-2-0-0-error-0x7e-message).

**Comment by LazyFrankB** [comment]
GTK installation was successful too ... installed before WeasyPrint installation.
"For Python 3.8+ and weasyprint 54+ you can manually set the path to your GTK3+ library with the environment variable WEASYPRINT_DLL_DIRECTORIES" 
How to set  environment variable?
